### ISSUE TITLE
Error getting objects in Centos8

### ISSUE THREAD

**Issue by SantiagoAndresHurtado** [danni/python-pkcs11#103]
Hi! 

SO: Centos 8.2.2004 
library version: python-pkcs11(0.7.0)
python version: python3.8

I'm trying to read a certificate from my token (epass2003) but i get this error: 

`Traceback (most recent call last):`
`File "test.py", line 131, in <module>` 
    `signer('aGFzaCBzaGEyNTY=', 'qwerty123456', 1)`
  `File "test.py", line 109, in signer`
    `for obj in session.get_objects(attrs=None):`
  `File "pkcs11/_pkcs11.pyx", line 322, in pkcs11._pkcs11.SearchIter.__next__`
  `File "pkcs11/_pkcs11.pyx", line 678, in pkcs11._pkcs11.Object._make`
  `File "pkcs11/_pkcs11.pyx", line 733, in pkcs11._pkcs11.Object.__getitem__`
  `File "pkcs11/_utils.pyx", line 35, in pkcs11._pkcs11._unpack_attributes`
  `File "/usr/local/lib64/python3.6/site-packages/pkcs11/defaults.py", line 132, in <lambda>`
    `lambda v: type_(unpack(v)))`
  `File "/usr/lib64/python3.6/enum.py", line 293, in __call__`
    `return cls.__new__(cls, value)`
  `File "/usr/lib64/python3.6/enum.py", line 535, in __new__`
    `return cls._missing_(value)`
  `File "/usr/lib64/python3.6/enum.py", line 548, in _missing_`
    `raise ValueError("%r is not a valid %s" % (value, cls.__name__))`
`ValueError: 94390496264193 is not a valid ObjectClass`

If i execute the same code in Ubuntu flavour it works fine!

[librarylibcastle.zip](https://github.com/danni/python-pkcs11/files/5538326/librarylibcastle.zip)

**Comment by danni** [comment]
It sounds like there's some mismatch in the type of something. What compiler toolchain are you using on what architecture? What pkcs#11 library?

**Comment by SantiagoAndresHurtado** [comment]
Hi!

I am not really sure what a toolchain is, but i give you some information that can be useful.

**Command executed:** yum list installed | grep gcc

> gcc.x86_64                                         8.3.1-5.el8.0.2                                @AppStream
> gcc-c++.x86_64                                  8.3.1-5.el8.0.2                                @AppStream
> libgcc.x86_64                                      8.3.1-5.el8.0.2                                @anaconda 

**SO:** Centos 8.2.2004 
**Architecture:** x86_64
**Kernel:** 4.18.0-193.19.1.el8_2.x86_64
**Processor:** Intel(R) Xeon(R) Bronze 3106 CPU @ 1.70GHz
**Library version:** python-pkcs11(0.7.0)
**Python version:** python3.8
**gcc version:** 8.3.1 20191121 (Red Hat 8.3.1-5) (GCC)

**.so library:** [librarylibcastle.zip](https://github.com/danni/python-pkcs11/files/5560781/librarylibcastle.zip)

Thanks for your help!

**Comment by danni** [comment]
Do you have the complete build log?

**Comment by SantiagoAndresHurtado** [comment]
¿How can i get it?

**Comment by danni** [comment]
Okay, I think this is the same bug as https://github.com/danni/python-pkcs11/issues/70 but maybe in a different place. The epass lib doesn't set the higher bytes of the value, just the lower bytes, and so we're relying on what's in the stack.

Add some debugging around line 744 of `_pkcs11.pyx` and see what value is before we send it to the HSM. I'm guessing it hasn't been zeroed correctly.

**Comment by SantiagoAndresHurtado** [comment]
Hi!

I made some debug: 

![__make](https://user-images.githubusercontent.com/25082424/100028802-b2fe2100-2dbd-11eb-8439-7f37afbb96c2.png)
**Object_class does not appear in console**

![_getitem_](https://user-images.githubusercontent.com/25082424/100028835-c8734b00-2dbd-11eb-99ca-05749edafec0.png)
**key is equal to 0**

![__setitem__](https://user-images.githubusercontent.com/25082424/100028854-cf01c280-2dbd-11eb-9c1e-06b5bd9b2d0d.png)
**key and value do not appear in console**

If I execute the same code in Ubuntu Server 20.04 instead of Centos 8.2.2004 it works well. 
¿Could the error be something else instead of the Library?
