### ISSUE TITLE
AttributeError: module 'pkcs11.util' has no attribute 'rsa'

### ISSUE THREAD

**Issue by oclemotthiqa** [danni/python-pkcs11#128]
Running MacOS 11.15.2
python-pkcs11 works very well (including util.) as I'm able to work with attached smart card (generate key and signing key is ok with various hardware)

Unfortunately, as I need to import a P12 in it I need to rely upon : pkcs11.util.rsa.decode_rsa_private_key(pkey)

and got this:
Traceback (most recent call last):
  File "signaturelib/signaturelib.py", line 131, in <module>
    importp12('test.p12', "1234".encode())
  File "signaturelib/signaturelib.py", line 114, in importp12
    dict = pkcs11.util.rsa.decode_rsa_private_key(pkey)
AttributeError: module 'pkcs11.util' has no attribute 'rsa'

Any idea ?

**Comment by oclemotthiqa** [comment]
Sorry, wrong imports on my side
