### ISSUE TITLE
Can't extract public key from Nitrokey HSM after creation

### ISSUE THREAD

**Issue by robertocal** [danni/python-pkcs11#151]
I am trying to extract the public key from a Nitrokey HSM after creating a RSA key but it gives me an error.

```
import pkcs11
from pkcs11 import KeyType, ObjectClass, Mechanism
from pkcs11.util.rsa import encode_rsa_public_key

from Crypto.PublicKey import RSA
from Crypto.Cipher import PKCS1_v1_5

lib = pkcs11.lib('/usr/lib/x86_64-linux-gnu/pkcs11/opensc-pkcs11.so')
token = lib.get_token()

# Open a session on our token
with token.open(user_pin='***', rw=True) as session:
    # Generate an RSA keypair in this session
    pub, priv = session.generate_keypair(pkcs11.KeyType.RSA, 2048)

# Extract public key
key = session.get_key(key_type=KeyType.RSA, object_class=ObjectClass.PUBLIC_KEY)
key = RSA.importKey(encode_rsa_public_key(key))

# Encryption on the local machine
cipher = PKCS1_v1_5.new(key)
crypttext = cipher.encrypt(b'Data to encrypt')

# Decryption in the HSM
priv = session.get_key(key_type=KeyType.RSA, object_class=ObjectClass.PRIVATE_KEY)

plaintext = priv.decrypt(crypttext, mechanism=Mechanism.RSA_PKCS)
```

The following is the error I get:

```
Exception ignored in: <bound method SearchIter.__del__ of <pkcs11._pkcs11.SearchIter object at 0x7ff1e3c77820>>
Traceback (most recent call last):
  File "pkcs11/_pkcs11.pyx", line 326, in pkcs11._pkcs11.SearchIter.__del__
  File "pkcs11/_pkcs11.pyx", line 336, in pkcs11._pkcs11.SearchIter._finalize
  File "pkcs11/_errors.pyx", line 88, in pkcs11._pkcs11.assertRV
pkcs11.exceptions.SessionHandleInvalid: 
Traceback (most recent call last):
  File "/home/roberto/PycharmProjects/pythonProject/prova4.py", line 17, in <module>
    key = session.get_key(key_type=KeyType.RSA, object_class=ObjectClass.PUBLIC_KEY)
  File "/home/roberto/PycharmProjects/pythonProject/venv/lib/python3.10/site-packages/pkcs11/types.py", line 320, in get_key
    iterator = self.get_objects(attrs)
  File "pkcs11/_pkcs11.pyx", line 369, in pkcs11._pkcs11.Session.get_objects
  File "pkcs11/_pkcs11.pyx", line 303, in pkcs11._pkcs11.SearchIter.__init__
  File "pkcs11/_errors.pyx", line 88, in pkcs11._pkcs11.assertRV
pkcs11.exceptions.SessionHandleInvalid
```

**Comment by mskalski** [comment]
# Open a session on our token
with token.open(user_pin='***', rw=True) as session:
    # Generate an RSA keypair in this session
    pub, priv = session.generate_keypair(pkcs11.KeyType.RSA, 2048)

**Comment by mskalski** [comment]
PS Sorry for first comment, edited it accordingly

**Comment by robertocal** [comment]
No, it was not intentional. Thank you for the clarification.
