### ISSUE TITLE
ValueError exception on lib.getToken call

### ISSUE THREAD

**Issue by Dean151** [danni/python-pkcs11#2]
Hi !
While giving a try with your library, I encounter a valueError  with this code : 
```
import pkcs11
lib = pkcs11.lib('/opt/tw_proteccio/lib/libnethsm.so')
token = lib.get_token(token_label='test_equity')
```

Witch give me : 
```
Traceback (most recent call last):
  File "aes.py", line 6, in <module>
    token = lib.get_token(token_label='test_equity')
  File "pkcs11/_pkcs11.pyx", line 1248, in pkcs11._pkcs11.lib.get_token (pkcs11/_pkcs11.c:24462)
  File "pkcs11/_pkcs11.pyx", line 1211, in get_tokens (pkcs11/_pkcs11.c:23758)
  File "pkcs11/_pkcs11.pyx", line 188, in pkcs11._pkcs11.Slot.get_mechanisms (pkcs11/_pkcs11.c:6010)
  File "pkcs11/_utils.pyx", line 18, in pkcs11._pkcs11.CK_ULONG_buffer (pkcs11/_pkcs11.c:3371)
  File "stringsource", line 151, in View.MemoryView.array.__cinit__ (pkcs11/_pkcs11.c:25089)
ValueError: Invalid shape in axis 0: 0.
```

**Comment by Dean151** [comment]
This is the HSM status : 
```
Bull TrustWay Proteccio NetHSM 2.11
Configuration case 2 read from ./proteccio.rc
Library Info:
cryptoki Version:	2.11
manufacturer ID:	Bull TrustWay Proteccio         
library Description:	nethsm PKCS#11 RPC              
libraryVersion:	2.11

Token Info:
tokenInfo Version:	0
Virtual Token state:	0X1040
Extented state:		0X200
MCS Version:		65539
FPGA Version:		138
CRYPTO Version:		138
Firmware Version:	138
Serial Number:		81604-0050000369
Index			0
slot flags		0X0
token flags		0X0

	Token (Slot 1) 	Token Info:
	Virtual Token state:	0X40
	Extented state:		0X0
	slot flags		0X5
	token flags		0X0
	Label:			test_equity   
```

**Comment by danni** [comment]
Ah, it looks like you don't support any mechanisms, and the code isn't handling that.

**Comment by danni** [comment]
I'll make a release that fixes the `ValueError`, but why it would think you have no mechanisms is strange.

**Comment by danni** [comment]
Released v0.2.2

**Comment by Dean151** [comment]
Maybe we have a configuration issue right into our HSM ; it's very new for us, and we are experimenting it. I will check the configuration, thank you for your time !

**Comment by danni** [comment]
Are you using a virtual slot? Maybe it requires some form of initialisation, or an environment variable being set in PKCS#11. Let me know how it goes, it would be good to update the support matrix, fix any issues.

**Comment by Dean151** [comment]
Well ; the "aes.py" example works well now. We indeed use a virtual slot on our hsm.
Thanks for your fix !
