### ISSUE TITLE
TypeError: Expected str, got unicode

### ISSUE THREAD

**Issue by mzobe** [danni/python-pkcs11#5]
Platform : MacOS
python 2.7

Code which gives errors:

from pkcs11  import Attribute,KeyType,lib ,Slot,ObjectClass
import os

# Initialise our PKCS#11 library
lib = lib(str(os.environ['PKCS11_MODULE']))

error:

/usr/local/bin/python2.7 /client.py
Traceback (most recent call last):
  File "/Users/roboguru/learnpython/softhsm/client.py", line 5, in <module>
    lib = lib(str(os.environ['PKCS11_MODULE']))
  File "/usr/local/lib/python2.7/site-packages/pkcs11/__init__.py", line 36, in lib
    _lib = _pkcs11.lib(so)
  File "pkcs11/_pkcs11.pyx", line 1169, in pkcs11._pkcs11.lib.__init__ (pkcs11/_pkcs11.c:22662)
TypeError: Expected str, got unicode

**Comment by danni** [comment]
Hi, the library doesn't support Python 2.7. Upgrade to Python 3.4 or later :)
