### ISSUE TITLE
_fix_string_length clips last character if string length >= size

### ISSUE THREAD

**Issue by asaero** [danni/python-pkcs11#63]
If the string being passed to  `_fix_string_length` is equal to or longer than the `size` argument, the last character gets clipped off.
For example, if I run the test_slots_and_tokens unit test with a token label of 32 characters, it fails like so:

### Command
```
PKCS11_TOKEN_SO_PIN=654321 PKCS11_TOKEN_PIN=123456 PKCS11_TOKEN_LABEL="73ef7a32521d4b568c462281e6a9ac4c" PKCS11_MODULE='libsofthsm2.so' python3 -m unittest -v tests.test_slots_and_tokens
```
### Error
```
======================================================================
FAIL: test_get_token (tests.test_slots_and_tokens.SlotsAndTokensTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "python-pkcs11/tests/test_slots_and_tokens.py", line 72, in test_get_token
    self.assertEqual(token.label, TOKEN)
AssertionError: '73ef7a32521d4b568c462281e6a9ac4' != '73ef7a32521d4b568c462281e6a9ac4c'
- 73ef7a32521d4b568c462281e6a9ac4
+ 73ef7a32521d4b568c462281e6a9ac4c
?                                +
```
It looks like this is because the `_fix_string_length` function is adding a null character as position `size - 1`; I think this should just be `string[size] = b'\0'`. Because pkcs11 pads strings less than the maximum size, this doesn't appear to cause a problem until the string is at least the same length as the `size` argument, whereupon the last character is clipped off.

**Comment by danni** [comment]
It might not be quite that simple, I expect you'll segfault adding a byte past the end of the buffer. You might need to duplicate the string into a `size + 1` buffer. Given it's a n byte string, that we want to be an n byte string + 1 nul.

Are you able to make a pull request?

**Comment by asaero** [comment]
Ah yes, you're right. I had been doing some debugging, and found that using `size` was "fixing" my problem by getting the correct label length, but this is because the "label" in `the CK_TOKEN_INFO info` object is actually comprised of "label", "model", "manufacturerID", and "serial". I had ended up replacing the first character of "model" with a `nul`, which is why `string[size]` had worked; side-effect of this was the "model" value ended up being empty, since it started with `nul`.

On that note, it did surprise me a bit that the string fields of `CK_TOKEN_INFO` all seem to point to the same buffer; is this expected? For example, here's the contents of the `info` object in `Slot.get_token()` for one of my debug runs:
```
{'firmwareVersion': {'major': 2, 'minor': 5},
 'flags': 1069,
 'hardwareVersion': {'major': 2, 'minor': 5},
 'label': b'12345678123456781234567812345678SoftHSM project                 '
          b'SoftHSM v2      e32f42014cb7fc54-\x04',
 'manufacturerID': b'SoftHSM project                 SoftHSM v2      e32f4201'
                   b'4cb7fc54-\x04',
 'model': b'SoftHSM v2      e32f42014cb7fc54-\x04',
 'serialNumber': b'e32f42014cb7fc54-\x04',
 'ulFreePrivateMemory': 18446744073709551615,
 'ulFreePublicMemory': 18446744073709551615,
 'ulMaxPinLen': 255,
 'ulMaxRwSessionCount': 0,
 'ulMaxSessionCount': 0,
 'ulMinPinLen': 4,
 'ulRwSessionCount': 18446744073709551615,
 'ulSessionCount': 18446744073709551615,
 'ulTotalPrivateMemory': 18446744073709551615,
 'ulTotalPublicMemory': 18446744073709551615,
 'utcTime': b'2019082909073800\xff~'}
```
This also seems to be the same for `CK_SLOT_INFO`.

Anyway, I can fix the behaviour by doing this:
```python
    def get_token(self):
        cdef CK_TOKEN_INFO info

        assertRV(_funclist.C_GetTokenInfo(self.slot_id, &info))

        label = info.label[:sizeof(info.label)]
        serialNumber = info.serialNumber[:sizeof(info.serialNumber)]
        model = info.model[:sizeof(info.model)]
        manufacturerID = info.manufacturerID[:sizeof(info.manufacturerID)]

        return Token(self, label, serialNumber, model, manufacturerID,
                     info.hardwareVersion, info.firmwareVersion, info.flags)
```

Does that look like a good solution?

**Comment by danni** [comment]
> On that note, it did surprise me a bit that the string fields of CK_TOKEN_INFO all seem to point to the same buffer; is this expected?

Yes, because they're all set in the same struct that's passed into PKCS#11, so the block is n bytes of chars, followed by m bytes of chars.

If using a slice works for doing the duplication, then I would be happy to replace `_fix_string_length` with `str[:size]`. That's quite neat.

**Comment by asaero** [comment]
Yeah, slicing the string like and assigning it to a Python bytes object also performs a copy of the data.
I'll go ahead and put together a pull request.

**Comment by asaero** [comment]
So, I can now pass the test test_slots_and_tokens test with a label of 32 characters. However, I'm getting failures on the test_x509 and test_ecc cases (both on my branch, and on master):

### test_x509
#### Test Output
```
test_import_ca_certificate (tests.test_x509.X509Tests) ... ok
test_import_ca_certificate_easy (tests.test_x509.X509Tests) ... ok
test_self_sign_certificate (tests.test_x509.X509Tests) ... CN = Test Certificate
error 18 at 0 depth lookup: self signed certificate
FAIL
test_sign_csr (tests.test_x509.X509Tests) ... verify OK
ok
test_verify_certificate_dsa (tests.test_x509.X509Tests) ... ok
test_verify_certificate_ecdsa (tests.test_x509.X509Tests) ... skipped 'Requires Mechanism.ECDSA_SHA1'
test_verify_certificate_rsa (tests.test_x509.X509Tests) ... ok

======================================================================
FAIL: test_self_sign_certificate (tests.test_x509.X509Tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aidan/work/python-pkcs11/tests/__init__.py", line 95, in wrapper
    return func(self, *args, **kwargs)
  File "/home/aidan/work/python-pkcs11/tests/test_x509.py", line 222, in test_self_sign_certificate
    self.assertEqual(proc.wait(), 0)
AssertionError: 2 != 0

----------------------------------------------------------------------
Ran 7 tests in 0.094s

FAILED (failures=1, skipped=1)
Test failed: <unittest.runner.TextTestResult run=7 errors=0 failures=1>
error: Test failed: <unittest.runner.TextTestResult run=7 errors=0 failures=1>
```
### test_ecc
#### Test Output
```
test_derive_key (tests.test_ecc.ECCTests) ... ERROR
test_import_key_named_curve (tests.test_ecc.ECCTests) ... skipped 'Requires Mechanism.ECDSA_SHA1'
test_import_key_pair (tests.test_ecc.ECCTests) ... ok
test_import_key_params (tests.test_ecc.ECCTests) ... ok
test_sign_ecdsa (tests.test_ecc.ECCTests) ... ok
test_sign_eddsa (tests.test_ecc.ECCTests) ... ERROR

======================================================================
ERROR: test_derive_key (tests.test_ecc.ECCTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aidan/work/python-pkcs11/tests/__init__.py", line 95, in wrapper
    return func(self, *args, **kwargs)
  File "/home/aidan/work/python-pkcs11/tests/test_ecc.py", line 43, in test_derive_key
    alice_pub, alice_priv = parameters.generate_keypair()
  File "pkcs11/_pkcs11.pyx", line 740, in pkcs11._pkcs11.DomainParameters.generate_keypair
    assertRV(_funclist.C_GenerateKeyPair(self.session._handle,
  File "pkcs11/_errors.pyx", line 88, in pkcs11._pkcs11.assertRV
    raise ERROR_MAP.get(rv,
pkcs11.exceptions.GeneralError

======================================================================
ERROR: test_sign_eddsa (tests.test_ecc.ECCTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aidan/work/python-pkcs11/tests/__init__.py", line 95, in wrapper
    return func(self, *args, **kwargs)
  File "/home/aidan/work/python-pkcs11/tests/test_ecc.py", line 159, in test_sign_eddsa
    pub, priv = parameters.generate_keypair()
  File "pkcs11/_pkcs11.pyx", line 740, in pkcs11._pkcs11.DomainParameters.generate_keypair
    assertRV(_funclist.C_GenerateKeyPair(self.session._handle,
  File "pkcs11/_errors.pyx", line 88, in pkcs11._pkcs11.assertRV
    raise ERROR_MAP.get(rv,
pkcs11.exceptions.GeneralError

----------------------------------------------------------------------
Ran 6 tests in 0.013s

FAILED (errors=2, skipped=1)
Test failed: <unittest.runner.TextTestResult run=6 errors=2 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=6 errors=2 failures=0>
```
These are errors from the Journal when running test_ecc:
```
python3[25382]: OSSLECDSA.cpp(304): ECDSA key generation failed (0x100AE081)
python3[25382]: SoftHSM.cpp(8689): Could not generate key pair
python3[25382]: OSSLECDSA.cpp(304): ECDSA key generation failed (0x10108077)
python3[25382]: SoftHSM.cpp(8689): Could not generate key pair
```

Do you have any thoughts on these errors?

**Comment by danni** [comment]
I suspect your OpenSSL config doesn't want to validate self-signed certificates, maybe without an extra flag.

I don't know why it can't generate the EC key here. Maybe you don't have the curve it wants available.

If you push your branch, we can test it against the CI.

**Comment by asaero** [comment]
I've opened up a pull request with the changes now. 
Looks like Travis seems to have an updated version of Openssl now as well, so I've removed the expected failure on `test_aes.test_wrap`; this got all the tests passing.

**Comment by danni** [comment]
Thanks!
