### ISSUE TITLE
Error when installing in Windows

### ISSUE THREAD

**Issue by LilyNL** [danni/python-pkcs11#69]
Hi all,

I got errors when installing the package in Windows with python 3.6, 64bit, see below.
Could any of you help me on this?
TIA.
Regards,
Lily.

1. Using command python setup.py build with code downloaded from git repository```

```
C:\temp\python-pkcs11-master>python setup.py build
Traceback (most recent call last):
  File "setup.py", line 59, in <module>
    test_suite='tests',
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\setuptools\__init__.py", line 143, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\distutils\core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\setuptools\dist.py", line 442, in __init__
    k: v for k, v in attrs.items()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\distutils\dist.py", line 281, in __init__
    self.finalize_options()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\setuptools\dist.py", line 601, in finalize_options
    ep.load()(self, ep.name, value)
  File "c:\temp\python-pkcs11-master\.eggs\setuptools_scm-3.3.3-py3.6.egg\setuptools_scm\integration.py", line 17, in version_keyword
    dist.metadata.version = get_version(**value)
  File "c:\temp\python-pkcs11-master\.eggs\setuptools_scm-3.3.3-py3.6.egg\setuptools_scm\__init__.py", line 150, in get_version
    parsed_version = _do_parse(config)
  File "c:\temp\python-pkcs11-master\.eggs\setuptools_scm-3.3.3-py3.6.egg\setuptools_scm\__init__.py", line 113, in _do_parse
    "use git+https://github.com/user/proj.git#egg=proj" % config.absolute_root
LookupError: setuptools-scm was unable to detect version for 'C:\\temp\\python-pkcs11-master'.

Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj

```
2. Use command pip install python-pkcs1

```
C:\temp\python-pkcs11-master>pip install python-pkcs11
Collecting python-pkcs11
  Using cached https://files.pythonhosted.org/packages/4a/6a/df6eeb9565c937b227c60d06907cd2c2184d6c65578d97b95a39c08748e0/python-pkcs11-0.5.0.tar.gz
Requirement already satisfied: asn1crypto in c:\users\admin\appdata\local\programs\python\python36\lib\site-packages (from python-pkcs11) (1.3.0)
Requirement already satisfied: cached-property in c:\users\admin\appdata\local\programs\python\python36\lib\site-packages (from python-pkcs11) (1.5.1)
Installing collected packages: python-pkcs11
    Running setup.py install for python-pkcs11 ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\admin\appdata\local\programs\python\python36\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\admin\\AppData\\Local\\Temp\\pip-install-fyx57k7w\\python-pkcs11\\setup.py'"'"'; __file__='"'"'C:\\Users\\admin\\AppData\\Local\\Temp\\pip-install-fyx57k7w\\python-pkcs11\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\admin\AppData\Local\Temp\pip-record-0wp5mqdv\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\admin\AppData\Local\Temp\pip-install-fyx57k7w\python-pkcs11\
    Complete output (46 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\pkcs11
    copying pkcs11\constants.py -> build\lib.win-amd64-3.6\pkcs11
    copying pkcs11\defaults.py -> build\lib.win-amd64-3.6\pkcs11
    copying pkcs11\exceptions.py -> build\lib.win-amd64-3.6\pkcs11
    copying pkcs11\mechanisms.py -> build\lib.win-amd64-3.6\pkcs11
    copying pkcs11\types.py -> build\lib.win-amd64-3.6\pkcs11
    copying pkcs11\__init__.py -> build\lib.win-amd64-3.6\pkcs11
    creating build\lib.win-amd64-3.6\pkcs11\util
    copying pkcs11\util\dh.py -> build\lib.win-amd64-3.6\pkcs11\util
    copying pkcs11\util\dsa.py -> build\lib.win-amd64-3.6\pkcs11\util
    copying pkcs11\util\ec.py -> build\lib.win-amd64-3.6\pkcs11\util
    copying pkcs11\util\rsa.py -> build\lib.win-amd64-3.6\pkcs11\util
    copying pkcs11\util\x509.py -> build\lib.win-amd64-3.6\pkcs11\util
    copying pkcs11\util\__init__.py -> build\lib.win-amd64-3.6\pkcs11\util
    running egg_info
    writing python_pkcs11.egg-info\PKG-INFO
    writing dependency_links to python_pkcs11.egg-info\dependency_links.txt
    writing requirements to python_pkcs11.egg-info\requires.txt
    writing top-level names to python_pkcs11.egg-info\top_level.txt
    reading manifest file 'python_pkcs11.egg-info\SOURCES.txt'
    writing manifest file 'python_pkcs11.egg-info\SOURCES.txt'
    copying pkcs11\_errors.pyx -> build\lib.win-amd64-3.6\pkcs11
    copying pkcs11\_loader.pyx -> build\lib.win-amd64-3.6\pkcs11
    copying pkcs11\_pkcs11.pyx -> build\lib.win-amd64-3.6\pkcs11
    copying pkcs11\_pkcs11_defn.pxd -> build\lib.win-amd64-3.6\pkcs11
    copying pkcs11\_utils.pyx -> build\lib.win-amd64-3.6\pkcs11
    running build_ext
    cythoning pkcs11/_loader.pyx to pkcs11\_loader.c
    c:\users\admin\appdata\local\temp\pip-install-fyx57k7w\python-pkcs11\.eggs\cython-0.29.14-py3.6-win-amd64.egg\Cython\Compiler\Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: C:\Users\admin\AppData\Local\Temp\pip-install-fyx57k7w\python-pkcs11\pkcs11\_loader.pyx
      tree = Parsing.p_module(s, pxd, full_module_name)
    cythoning pkcs11/_pkcs11.pyx to pkcs11\_pkcs11.c
    c:\users\admin\appdata\local\temp\pip-install-fyx57k7w\python-pkcs11\.eggs\cython-0.29.14-py3.6-win-amd64.egg\Cython\Compiler\Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: C:\Users\admin\AppData\Local\Temp\pip-install-fyx57k7w\python-pkcs11\pkcs11\_pkcs11.pyx
      tree = Parsing.p_module(s, pxd, full_module_name)
    building 'pkcs11._loader' extension
    creating build\temp.win-amd64-3.6
    creating build\temp.win-amd64-3.6\Release
    creating build\temp.win-amd64-3.6\Release\pkcs11
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\admin\appdata\local\programs\python\python36\include -Ic:\users\admin\appdata\local\programs\python\python36\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\winrt" /Tcpkcs11\_loader.c /Fobuild\temp.win-amd64-3.6\Release\pkcs11\_loader.obj
    _loader.c
    pkcs11\_loader.c(596): fatal error C1083: Cannot open include file: 'dlfcn.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\admin\appdata\local\programs\python\python36\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\admin\\AppData\\Local\\Temp\\pip-install-fyx57k7w\\python-pkcs11\\setup.py'"'"'; __file__='"'"'C:\\Users\\admin\\AppData\\Local\\Temp\\pip-install-fyx57k7w\\python-pkcs11\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\admin\AppData\Local\Temp\pip-record-0wp5mqdv\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.
```

**Comment by danni** [comment]
I'm not sure why it's complaining about not having a git repository if you're in a git repository, but try `python setup.py install`.

**Comment by LilyNL** [comment]
Thank you for your help! It works.

In my previous steps, I did not make a local repository (just downloaded and unzipped).

To save time of other beginners, below are what I did:
- Use git to have a local repository of the master branch
- Go to the root directory of the local repository, use two commands: (not sure if the second is enough)
```
python setup.py build
python setup.py install
```

It would help if you update the pages at
https://python-pkcs11.readthedocs.io/en/latest/
https://pypi.org/project/python-pkcs11/

**Comment by praffulkapil** [comment]
Hi Danni,

I'm getting the issue while trying to install this PKCS11 package. I'm using Anaconda3 distribution (Python version 3.7.6).
Tried all possible method from this forum. Can you Please help me ?

`C:\Data\Learning\Pyhton\HSM\python-pkcs11-master>python setup.py install
Traceback (most recent call last):
  File "setup.py", line 60, in <module>
    test_suite='tests',
  File "C:\Users\praff\anaconda3\lib\site-packages\setuptools\__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\praff\anaconda3\lib\distutils\core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "C:\Users\praff\anaconda3\lib\site-packages\setuptools\dist.py", line 448, in __init__
    k: v for k, v in attrs.items()
  File "C:\Users\praff\anaconda3\lib\distutils\dist.py", line 292, in __init__
    self.finalize_options()
  File "C:\Users\praff\anaconda3\lib\site-packages\setuptools\dist.py", line 740, in finalize_options
    ep.load()(self)
  File "C:\Users\praff\anaconda3\lib\site-packages\setuptools\dist.py", line 747, in _finalize_setup_keywords
    ep.load()(self, ep.name, value)
  File "c:\data\learning\pyhton\hsm\python-pkcs11-master\.eggs\setuptools_scm-4.1.2-py3.7.egg\setuptools_scm\integration.py", line 17, in version_keyword
    dist.metadata.version = _get_version(config)
  File "c:\data\learning\pyhton\hsm\python-pkcs11-master\.eggs\setuptools_scm-4.1.2-py3.7.egg\setuptools_scm\__init__.py", line 148, in _get_version
    parsed_version = _do_parse(config)
  File "c:\data\learning\pyhton\hsm\python-pkcs11-master\.eggs\setuptools_scm-4.1.2-py3.7.egg\setuptools_scm\__init__.py", line 118, in _do_parse
    "use git+https://github.com/user/proj.git#egg=proj" % config.absolute_root
LookupError: setuptools-scm was unable to detect version for 'C:\\Data\\Learning\\Pyhton\\HSM\\python-pkcs11-master'.

Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj

C:\Data\Learning\Pyhton\HSM\python-pkcs11-master>`
