### ISSUE TITLE
when

### ISSUE THREAD

**Issue by snny000** [danni/python-pkcs11#81]

**Comment by snny000** [comment]
The code is:
strtypeE = '/ukey/libshuttle_p11v220.so.1.0.0'
so_file = strtypeE.decode('gbk')
lib = pkcs11.lib(so_file)
print(list(lib.get_tokens()))
But when i run python code ,i has error is below:
Traceback (most recent call last):
  File "pkcs11_test.py", line 10, in <module>
    print(list(lib.get_tokens()))
  File "pkcs11/_pkcs11.pyx", line 1313, in get_tokens
  File "pkcs11/_pkcs11.pyx", line 1298, in pkcs11._pkcs11.lib.get_slots
  File "build/bdist.linux-x86_64/egg/pkcs11/types.py", line 118, in __init__
    
  File "/virtualenv/detect_env/lib/python2.7/site-packages/aenum/__init__.py", line 2042, in __call__
    return cls.__new__(cls, value)
  File "/virtualenv/detect_env/lib/python2.7/site-packages/aenum/__init__.py", line 2414, in __new__
    raise exc
ValueError: 7L is not a valid SlotFlag
