### ISSUE TITLE
Unable to install the PKCS11 library

### ISSUE THREAD

**Issue by praffulkapil** [danni/python-pkcs11#85]
Hi Danni,

I'm getting the issue while trying to install this PKCS11 package. I'm using Anaconda3 distribution (Python version 3.7.6).
Tried all possible method from this forum. Can you Please help me ?

I downloaded and unzipped your code. Then ran this ...

`C:\Data\Learning\Pyhton\HSM\python-pkcs11-master>python setup.py build
Traceback (most recent call last):
  File "setup.py", line 60, in <module>
    test_suite='tests',
  File "C:\Users\praff\anaconda3\lib\site-packages\setuptools\__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\praff\anaconda3\lib\distutils\core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "C:\Users\praff\anaconda3\lib\site-packages\setuptools\dist.py", line 448, in __init__
    k: v for k, v in attrs.items()
  File "C:\Users\praff\anaconda3\lib\distutils\dist.py", line 292, in __init__
    self.finalize_options()
  File "C:\Users\praff\anaconda3\lib\site-packages\setuptools\dist.py", line 740, in finalize_options
    ep.load()(self)
  File "C:\Users\praff\anaconda3\lib\site-packages\setuptools\dist.py", line 747, in _finalize_setup_keywords
    ep.load()(self, ep.name, value)
  File "c:\data\learning\pyhton\hsm\python-pkcs11-master\.eggs\setuptools_scm-4.1.2-py3.7.egg\setuptools_scm\integration.py", line 17, in version_keyword
    dist.metadata.version = _get_version(config)
  File "c:\data\learning\pyhton\hsm\python-pkcs11-master\.eggs\setuptools_scm-4.1.2-py3.7.egg\setuptools_scm\__init__.py", line 148, in _get_version
    parsed_version = _do_parse(config)
  File "c:\data\learning\pyhton\hsm\python-pkcs11-master\.eggs\setuptools_scm-4.1.2-py3.7.egg\setuptools_scm\__init__.py", line 118, in _do_parse
    "use git+https://github.com/user/proj.git#egg=proj" % config.absolute_root
LookupError: setuptools-scm was unable to detect version for 'C:\\Data\\Learning\\Pyhton\\HSM\\python-pkcs11-master'.

Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj

C:\Data\Learning\Pyhton\HSM\python-pkcs11-master>`

**Comment by danni** [comment]
Hi. Where did you get the code from? It's looking for a git repo to get the version number from. You either need to install from PyPI or from Git. See the tip in the backtrace.

**Comment by praffulkapil** [comment]
> Hi. Where did you get the code from? It's looking for a git repo to get the version number from. You either need to install from PyPI or from Git. See the tip in the backtrace.


pip install python-pkcs11 worked only after installation of  Microsoft VC++ 14.2  and win10 SDK
Hope it helps other users. It worked for me. I found it in other forums.
